### ISSUE TITLE
Update Notebooks + `test_ranges` dictionary

### ISSUE THREAD

**Issue by brihijoshi** [cltl/robustness-albert#1]
Hi! 

Thanks for putting up amazing work! I wanted to follow along with the paper and reproduce some of the results, however even with the given the test_suite pickle file, I am unable to find the `test_ranges` dictionary in the suite pickle file, which contains the range of samples in the example list that belong to a given test. I'd be very grateful if you can update that, as well as some of the notebooks which aggregate results across seeds. 

Looking forward to hearing from you!

**Comment by urjakh** [comment]
Hi Brihi! 

Happy to hear that you want to reproduce some of the results! 

To get the examples for the tests, `test_ranges` does not give the examples since all of the examples are linked to their respective separate test. 

So to access them, you can use the following code: 

```python 
test_names = test_suite.tests.keys()

# With the test names as a key, we can retrieve the specific test's examples using the 'data' attribute. 
examples = test_suite.tests[test_names[0]].data

```
Then, with `examples` you have all of the instances used for the first test capability. If you change the index in `test_names` you can get the examples of the other tests as well. 

Hope this clears it up, let me know if you have further questions! I will upload the notebooks today or tomorrow and notify you about it.

**Comment by urjakh** [comment]
Notebooks have been updated now! The notebooks relevant for the results are dev_set_results.ipynb and plot_checklist_results.ipynb.
